# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9049cc93d3b8ad62627ce6813b2245772cdf06972023474543db259ff0944f8106e1b625bcf38db5655ad15137057a903351cdeec307ca8bac3e7746cc0e00c0

test:
  secret_key_base: 4508dd82382b753a3664f60162137f51a038daf097f1064108ce95cccefb465df858d083dfe78fe791ff025745be742a3d4bbe2ba1c9114905d74097fa94087f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
